language: python
python:
  - "2.7"
  - "3.3" 
  - "3.4"
  - "3.5"

install:
  - sudo pip install conda
  - sudo conda init
  - deps='pip numpy scipy pandas nose matplotlib'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - python -m pip install python-coveralls coverage
  - "pip install -r requirements_test.txt"

script:
  - nosetests --with-coverage

after_success:
  - coveralls

