language: python
env:
  global:
    secure: dlKlpVXGzCuN1Wc0h48HeT3EYjND2erX6hPeya/c6SR9LTN+ybcWGyZrHDtybOaRw28REVIXqH3unkVtX/X4d46U/tmRcC/Fy7wInhOS82yuFRCB8TinQkpeqRDZuU+HiW737uzmYf3U37NZnm2VGCsvVXUAoZe6/aLgTXMHP6U=
  matrix:
    - PYTHON=2.7 PANDAS=0.19.2
    - PYTHON=2.7 PANDAS=0.20.2
    - PYTHON=3.5 PANDAS=0.18.1
    - PYTHON=3.5 PANDAS=0.19.2
    - PYTHON=3.5 PANDAS=0.20.2 COVERAGE=true

install:
  - if [[ "$PYTHON" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels pandas
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$PYTHON pip numpy scipy pandas=$PANDAS nose matplotlib requests
  - source activate test-environment
  - "pip install -r requirements_test.txt"
  - pip install flake8 python-coveralls coverage pytest

script:
  - if [[ "$PYTHON" == "2.7" ]]; then
      nosetests -v -s;
    else
      nosetests -v -s --with-coverage --cover-package=japandas;
    fi
  - flake8 --ignore E501 japandas

after_success:
  - if [ "$COVERAGE" ]; then
      coveralls;
    fi
